### ISSUE TITLE
Mistyped Link

### ISSUE THREAD

**Issue by code-reaper08** [Chandu71202/Marvel-Movie-Collection#1]
### Actual :
https://github.com/Chandu71202/Marvel-Movie-Collection/blob/92f5b4109d110592a89662ce79bf49168d35d7da/MARVEL.html#L22
### Should be : 

            <a href="./MARVEL PROJECT.html" style="color: white; text-decoration: none;">MARVEL</a>

**Comment by Chandu71202** [comment]
ThankYou Code Reaper i had modified it  :)
